language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

notifications:
  email: false

cache:
  directories:
    - $HOME/.nuget/packages/
    - $HOME/docker/

install: dotnet restore --source "$NUGET_SOURCE_URL"

script: ./scripts/ci/build-and-test.sh

deploy:
  - provider: script
    script: ./scripts/ci/deploy.sh
    skip_cleanup: true
    on:
      branch: mount-data
