language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: false

notifications:
  email: false

install:
  - dotnet restore --source "$NUGET_SOURCE_URL"

script:
  - dotnet publish -c Release --version-suffix $(./scripts/ci/version-suffix.sh)
  - docker build -t "$DOCKER_TAG" .

deploy:
  provider: script
  script: ./scripts/ci/deploy-docker.sh
  skip_cleanup: true
  on:
    branch: docker
