version: "3.4"
services:
  app:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    links:
      - db:database
  db:
    image: mysql
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
